### ISSUE TITLE
The plugin log showed 'exited with error' even if push work already succeeded

### ISSUE THREAD

**Issue by yamasaLine** [belitre/helm-push-artifactory-plugin#14]
+ OS: Gitlab runner with CentOs.
+ Plugin ver: **v1.0.0**
+ Helm ver: Helm 3.0.1

Hi there, I met some issue when trying to push Helm packaged tgz to our enterprise Artifactory. The plugin log showed errors but in fact the pushing work already done successfully(tgz uploaded and also the Helm index yaml updated). This would make my Gitlab ci job failing and the overall pipe failing, even if in fact it succeeded.

Please see the details:
![image](https://user-images.githubusercontent.com/19356295/71333361-a8675600-2574-11ea-9dc5-9f227cdd87d8.png)

**Comment by belitre** [comment]
Hi @yamasaLine 

Sorry for the delay with the answer :)

Looks like the user or token you are using doesn't have permissions to trigger the reindex in the repo and that what is failing, reindex is triggered after pushing the chart to the repo.

You can always skip the reindex operation adding the flag: `--skip-reindex`

Hope this helps!

Cheers.

**Comment by jbilliau-rcd** [comment]
im getting this myself, so glad I looked here! If we do --skip-reindex, Artifactory will just do the indexing on the server side, making this unnecessary and perfectly fine?
