### ISSUE TITLE
File path handling is broken on Windows

### ISSUE THREAD

**Issue by sfzhi** [belitre/helm-push-artifactory-plugin#25]
When using the plugin on Windows, the full path to the temporary file (`C:\Users\whatever\AppData\Local\Temp\...`) ends up in the Artifactory path.
The problem is that `UploadChartPackage(...)` (in pkg/artifactory/upload.go) uses `path.Base(...)` in line 51, where it should use `filepath.Base(...)` instead, just like in line 59.

**Comment by belitre** [comment]
Hi @sfzhi and thank you for opening the issue!

I'll try to fix this as soon as I have some time free :)

**Comment by belitre** [comment]
Hi @sfzhi ,

I just created the release v0.4.1 for Helm v2 that fixes the problem. I'll create the release v1.0.1 for Helm v3 soon... :)
