### ISSUE TITLE
What's the difference between helm-push and helm-push-artifactory-plugin please?

### ISSUE THREAD

**Issue by ezhishui** [belitre/helm-push-artifactory-plugin#29]
What's the difference between helm-push and helm-push-artifactory-plugin please?

**Comment by belitre** [comment]
Hi @ezhishui ,

[helm-push](https://github.com/chartmuseum/helm-push): Helm plugin to push chart package to [ChartMuseum](https://chartmuseum.com/)
[helm-push-artifactory-plugin](https://github.com/belitre/helm-push-artifactory-plugin): A helm plugin to push charts to [Artifactory](https://jfrog.com/artifactory/)

Cheers :)

**Comment by ezhishui** [comment]
Thank you very much!
