### ISSUE TITLE
helm version inside install_plugin.sh pulls both client and tiller version in v0.4.1

### ISSUE THREAD

**Issue by mshivanna** [belitre/helm-push-artifactory-plugin#36]
We are using gitlab ci/cd integrated with kubernetes. We are using alpine/helm:2.16.3 image to run  our stage. When we try to install helm-push-artifactory-plugin it complained 
` Error, this version of helm-push-artifactory-plugin is only for Helm v2`

We tried debugging:
`helm plugin install https://github.com/belitre/helm-push-artifactory-plugin --version v0.4.1 --debug

 [debug] cloning https://github.com/belitre/helm-push-artifactory-plugin to 
/root/.helm/cache/plugins/https-github.com-belitre-helm-push-artifactory-plugin

 [debug] setting version to "v0.4.1"

 [debug] symlinking /root/.helm/cache/plugins/https-github.com-belitre-helm-push-artifactory-plugin to /root/.helm/plugins/helm-push-artifactory-plugin

 [debug] loading plugin from /root/.helm/plugins/helm-push-artifactory-plugin

 [debug] running install hook: /bin/sh -c cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh

 Error, this version of helm-push-artifactory-plugin is only for Helm v2

 Please use --version v1.0.1 or higher to install the plugin

 Error: plugin install hook for "push-artifactory" exited with error`

When we looked at the install_plugin.sh 
`helm_version="$(helm version | grep "Version" | cut -d '"' -f 2 | cut -d '.' -f 1)"`
The above line has the following result
`helm version | grep "Version" | cut -d '"' -f 2 | cut -d '.' -f 1`
v2
v2
the above line pulls both client and tiller version and hence helm_version will have the value v2 v2 and hence the below check fails.

`supported_helm_version="v2"

helm_version="$(helm version | grep "Version" | cut -d '"' -f 2 | cut -d '.' -f 1)"

if [ "$helm_version" != "$supported_helm_version" ]; then
    echo "Error, this version of helm-push-artifactory-plugin is only for Helm $supported_helm_version"
    echo "Please use --version v1.0.1 or higher to install the plugin"
    exit 1
fi`

So this line `helm_version="$(helm version | grep "Version" | cut -d '"' -f 2 | cut -d '.' -f 1)"`
should be `helm_version="$(helm version --client | grep "Version" | cut -d '"' -f 2 | cut -d '.' -f 1)"`

**Comment by belitre** [comment]
Hi @mshivanna,

Thanks for finding this and for the PR, I'll merge it right now :)

**Comment by belitre** [comment]
Just created a new release with your change: https://github.com/belitre/helm-push-artifactory-plugin/releases/tag/v0.4.2

Thank you very much again :)
