### ISSUE TITLE
Request: Cross platform compatibility

### ISSUE THREAD

**Issue by webbertakken** [belitre/helm-push-artifactory-plugin#4]
Does not work on Windows based systems as it returns an error when trying to install the plugin;

```
Error: exec: "sh": executable file not found in %PATH%
```

**Comment by belitre** [comment]
Hi @webbertakken and sorry for the delay!

Ok, I never used helm on Windows, I'll try to find some free time to see how to make it work.... my guess is that it just needs a change in the plugin manifest to make it work on Windows. I'll check if I can prepare a machine with Windows and fix this... but I can't make any promises :(

**Comment by belitre** [comment]
Hi @webbertakken,

Though I wasn't able to make it work through `helm plugin install`... I added a windows version to the release, and I tested that just extracting the zip file in `$HELM_HOME/plugins` works.

Hope it helps!

**Comment by webbertakken** [comment]
Cheers!

If I get some time for it, I might have a look at how to get it to work with helm plugin install.

**Comment by belitre** [comment]
The problem with `helm plugin install` is that in the manifest file you declare an install script like:
```
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
```

And of course for linux and mac you can use a shell-script, I guess that if you add a .bat script it would work for windows, but then it wouldn't work for linux and mac... I don't know so much about .bat scripts and to be honest my windows environment is not the best for tests :D

I'll try to find some time tomorrow to test it, if it works with a .bat script I'll create a branch with a tag just for windows so you can use helm plugin install.
